### ISSUE TITLE
README.md needs to be changed to maintain copyright

### ISSUE THREAD

**Issue by HoshiYamazaki** [SynneK1337/luszOS#1]
I'd just like to interject for a moment. What you're referring to as luszOS, is in fact, KEN/luszOS, or as I've recently taken to calling it, KEN plus luszOS. luszOS is not an operating system unto itself, but rather another free component of a fully functioning KEN system made useful by the KEN corelibs, shell utilities and vital system components comprising a full OS as defined by SHIZIX.

Many computer users run a modified version of the KEN system every day, without realizing it. Through a peculiar turn of events, the version of KEN which is widely used today is often called "luszOS", and many of its users are not aware that it is basically the KEN system, developed by the KEN Project.

There really is a luszOS, and these people are using it, but it is just a part of the system they use. luszOS is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. luszOS is normally used in combination with the KEN operating system: the whole system is basically KEN with luszOS added, or KEN/luszOS. All the so-called "luszOS" distributions are really distributions of KEN/luszOS.

**Comment by HoshiYamazaki** [comment]
Also, luszOS is just KEN/lusz, not luszOS.

Thats a funny thing that you realize it after while.

**Comment by SynneK1337** [comment]
ciebie pojebalo chyba

**Comment by HoshiYamazaki** [comment]
> ciebie pojebalo chyba

Już dawno 💃 🙈 🤔
